[PHP]

; Decides whether PHP may expose the fact that it is installed on the server
; (e.g. by adding its signature to the Web server header).  It is no security
; threat in any way, but it makes it possible to determine whether you use PHP
; on your server or not.
; https://php.net/expose-php
expose_php = Off

; Enable the engine and JIT by default for performance optimisation, can disable if causing issues.
zend_extension=opcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.max_accelerated_files=60000

; JIT for 8.4, will need optimising for production use but though would enable as default for now (can disable is causing issues).
opcache.jit=tracing
opcache.jit_buffer_size=128M

; these are the default values but just to be explicit for development, can disable for production use.
opcache.validate_timestamps=1
opcache.revalidate_freq=0

[Date]

; Defines the default timezone used by the date functions
; https://php.net/date.timezone
date.timezone = "UTC"
