name: Build, sign and push PHP base Image on Shared Core ECR
run-name: Test, sign and push PHP base Image on Shared Core ECR

on:
  push:
    branches: 
    - feature/AWSRESET1-365

jobs:

  # notation_setup:
  #   uses: ./.github/workflows/notation-setup-action.yaml

  php-base-image-push:

    runs-on: ubuntu-latest

    env:
      AWS_REGION : ${{ secrets.DEV_AWS_REGION }} #Change to reflect your Region
      AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
    - uses: actions/checkout@v3

    - name: Set IMAGE_TAG
      run: | 
        IMAGE_SHA=$(echo $GITHUB_SHA | cut -c 1-6)
        echo "IMAGE_TAG=vol-php-fpm-7.4.0-alpine-fpm-$IMAGE_SHA" >> $GITHUB_ENV
  
    - name: setup Notation CLI
      uses: notaryproject/notation-action/setup@v1
      with:
        version: "1.0.0"
      
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  ${{ secrets.DEV_AWS_ROLE }}
        aws-region:  ${{vars.DVSA_AWS_REGION}}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Login to Shared Core ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build the Docker image
      run: |
        bash scripts/docker-build.sh
        #docker build -t ${{ secrets.ECR_BASE_URL }}:$IMAGE_TAG -f dockerfile . 

    - name: Push docker base image
      id: push-images
      run: |
          SHA=$(git rev-parse --short HEAD)

          # Iterate over JSON objects in build.json
          jq -c '.[]' build.json | while read -r results; do
          
              repoName=$(echo "$results" | jq -r '.repoName') 
              tag=$(echo "$results" | jq -r '.tag') 
              build=$(echo "$results" | jq -r '.build')
   
              if [ "$build" == "true" ]; then
                  docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repoName:$tag-$SHA
              else
                  echo "Not pushing - $repoName, build parameter equal to false"
              fi
          done
    
    - name: Sign base images
      run: |
          jq -c '.[]' build.json | while read -r results; do
            build=$(echo "$results" | jq -r '.build')
            repoName=$(echo "$results" | jq -r '.repoName')
            dockerFile=$(echo "$results" | jq -r '.dockerFile') 
            if [ "$build" == "true" ]; then
              notation sign $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repoName:$tag-$SHA --plugin "com.amazonaws.signer.notation.plugin" --id "${{ secrets.DEV_VOL_IMAGE_SIGNING_PROFILE }}" 
            else
              echo "Not linting - $repoName, build parameter equal to false"
            fi
          done
        
