name: Security

on:
  schedule:
    # Weekly on Monday at 00:00 UTC
    - cron: 0 0 * * 1

jobs:
  get-latest-version:
    name: Get latest version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest version
        id: tag
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

  docker:
    name: Docker
    needs:
      - get-latest-version
    strategy:
      fail-fast: false
      matrix:
        base:
          - php/7.4/fpm-nginx
          - php/8.0/fpm-nginx
          - php/8.2/fpm-nginx
          - php/8.3/fpm-nginx
          - php/8.0/cli
          - php/8.2/cli
          - php/8.3/cli
    uses: ./.github/workflows/docker.yaml
    with:
      image-version: ${{ needs.get-latest-version.outputs.tag }}
      dockerfile-directory: ${{ matrix.base }}
      repository: ${{ matrix.base }}
    permissions:
      contents: read
      id-token: write

